<a href="https://colab.research.google.com/github/vipin0761/pwskills_DS/blob/main/Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

import numpy as np
list = ['1','2','3','4','5']
array_list = np.array(object = list)

print(type(list))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [4]:
# Q2. Write a code to print the data type of each and every element of both the variables list and array_list.
for i in list:
  print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [5]:
for i in array_list:
  print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [6]:
# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


In [8]:
for i in num_list:
  for j in i:
    print(type(j))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [9]:
for i in num_array:
  for j in i:
    print(type(j))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [12]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

print(np.shape(num_array))
print(np.size(num_array))

(2, 3)
6


In [16]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]
i  = np.zeros([3,3])
print(i)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

id = np.identity(5)
print(id)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
